# Generated by Django 3.0 on 2022-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(),
        ),
    ]
