# Generated by Django 3.2.5 on 2022-06-28 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=1500)),
                ('difficulty', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=100)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_judge.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(verbose_name='Submitted On')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_judge.problems')),
            ],
        ),
    ]
